name: gwb-dc

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - Pillow
  - ipywidgets>=0.6.0
  - requests
  - mkl
  - pip:
    - pymatsolver
    - discretize
    - git+https://github.com/simpeg/simpegEM1D.git@simulation-jk
    - empymod
